select * from superstoredataset;
#alter table superstoredataset rename column ï»¿Row_ID to Row_ID;
SELECT * from superstoredataset order by Row_ID;
select  count(distinct Order_ID)  from superstoredataset ;
select  count(distinct Customer_ID) from superstoredataset;
select sum(Sales) from superstoredataset;
select avg(Sales) from superstoredataset;
select sum(Profit) from superstoredataset;
select avg(Profit) from superstoredataset;
select Category,sum(Sales) from superstoredataset group by Category;
#select Sub-Category,sum(Sales) from superstoredataset group by Sub-Category;
select Region,sum(Sales) from superstoredataset group by Region;
select State,sum(Sales) from superstoredataset group by State;
select Segment,sum(Sales) from superstoredataset group by Segment;
select  Product_Name, sum(sales)as ss from superstoredataset group by Product_Name order by ss desc limit 10;
select  Product_Name, sum(Profit)as sp from superstoredataset group by Product_Name order by sp desc limit 10;
select  Product_Name, sum(sales)as ss from superstoredataset group by Product_Name order by ss  limit 10;
select  Customer_Name, sum(sales)as ss from superstoredataset group by Customer_Name order by ss desc limit 10;
select  Customer_Name, sum(sales)as ss from superstoredataset group by Customer_Name;
select  Customer_Name, sum(Profit)as ss from superstoredataset group by Customer_Name;
select  Month_Name, sum(sales)as ss from superstoredataset group by Month_Name ;
select  Order_Year, sum(sales)as ss from superstoredataset group by Order_Year ;
select  Quarter, sum(sales)as ss from superstoredataset group by Quarter;
select  Ship_Mode, sum(sales)as ss from superstoredataset group by Ship_Mode ;
select  avg(Delivery_Days) from superstoredataset;
select  Ship_Mode, count(Delivery_Days)as cd from superstoredataset group by Ship_Mode ;
select  Category, sum(Profit)as sp from superstoredataset group by Category order by sp desc limit 1 ;
select  Category, sum(Profit)as sp from superstoredataset group by Category order by sp  limit 1 ;
select  State, sum(Profit)as sp from superstoredataset group by State order by sp desc limit 1 ;
commit;